### ISSUE TITLE
Update fibonacci to use temporary variables and local variables

### ISSUE THREAD

**Issue by unbalancedparentheses** [lambdaclass/cleopatra_cairo#129]
- https://www.cairo-lang.org/docs/how_cairo_works/consts.html#temporary-variables
- https://www.cairo-lang.org/docs/how_cairo_works/consts.html#local-variables

**Comment by unbalancedparentheses** [comment]
@HermanObst please check this

**Comment by Juan-M-V** [comment]
This issue seems to have been fixed in commit 4663538326e076fc439634f7802d3f25a669a1c6
Are we good to close it?
