### ISSUE TITLE
test `bitwise_integration_test` is failing

### ISSUE THREAD

**Issue by tdelabro** [lambdaclass/cleopatra_cairo#216]
```shell

running 1 test
test bitwise_integration_test ... FAILED

failures:

---- bitwise_integration_test stdout ----
thread 'bitwise_integration_test' panicked at 'Failed to deserialize program: IO(Os { code: 2, kind: NotFound, message: "No such file or directory" })', tests/bitwise_test.rs:11:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Could be great to either remove the test or put back the file.
Also you should probably have github run tests when pushing/merging to `main`

**Comment by Juan-M-V** [comment]
Hi, thanks for the issue. I've just removed and cloned the project locally. Running `make test` works just fine. We're on the process of moving all the cairo programs to cairo_programs. So during this some things may break easily locally and not be reflected on the github actions. 
Could you see if there are any .json files in your cairo_programs directory? This has caused problems before

**Comment by Juan-M-V** [comment]
I've run this again with #224. The tests seem to be working fine. The compiling of cairo programs is now mostly handled by make and I also added a clean command that should help tidying things up. 
If you have the time after the PR merges, would you mind checking if the test keeps failing?

**Comment by Oppen** [comment]
This seems to be fixed when using `make test`.
